// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Fridge API
//
//  Swagger 2.0 study - a fridge API
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
