// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Fridge API
 *
 * OpenAPI 3.0.0 study - a fridge API
 *
 * API version: 0.0.1
 */

package main

import (
	"log"
	"net/http"

	server "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	DefaultAPIService := server.NewDefaultAPIService()
	DefaultAPIController := server.NewDefaultAPIController(DefaultAPIService)

	router := server.NewRouter(DefaultAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
