@startuml
'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
 !include SoftwareDevelopment/DNA/C4/C4PUML/C4-PlantUML/C4_Component.puml

title Component-Level diagram for HW

' Container(dsgui, "DS GUI", "Client Configuration")
' Container(intelisell, "Intellisell", "Schedule selling")
' ContainerDb(atsedb, "ATSE DB", "Schedules, markets, ...")

Container(tuner, "Tuner", "separate process")
Container_Boundary(api, "HW") {
    Component(adapter, "TunerAdapter", "Implement TunerPort, Use HwPort")
    Component(application, "application.HwService", "Implement use cases, implement HwPort, use TunerPort")
    Component(domain, "domain.HwRoot", "implement business objects, rules & behavior")
    Component(infrastructure, "infrastructure", "define outer world communication ports")
    Rel(application, domain, "use")
    Rel(application, infrastructure, "use")
    Rel(adapter, application, "interact", "HwPort, TunerPort")
}
Rel_U(adapter, tuner, "IPC", "eg. gRpc")
@enduml
