# Note that the names: mongodb, nsqlookupd, nsqd are visible to other containers
# as network host names and should not be changed or TCP/IP communication
# between containers will be broken (see: envconfig.sh)
version: '3'
services:
  mongodb:
    image: mongo
    command: mongod --port 27017 --dbpath /tmp
    ports:
      - "27017:27017" # twittervotes, counter & api from socialpoll connect here
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160" # nsqd connects here
      - "4161:4161" # counter from socialpoll connects here (consumer)
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --data-path=/tmp
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150" # twittervotes from socialpoll connects here (producer)
  socialpoll:
    image: golang
    command: /home/deploy_and_run.sh
    depends_on:
      - mongodb
      - nsqd
    ports:
      - "8080:8080" # api (http endpoints; web connects here)
      - "8081:8081" # web (http server; firefox connects here)
    volumes:
      - .:/home