version: '3'
services:
  mongodb:
    image: mongo
    command: mongod --port 27017 --dbpath /data
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --data-path=/data  #--broadcast-address=${HOST_IP}
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    volumes:
      - ./data:/data
  socialpoll:
    image: golang
    command: /home/runall.sh
    depends_on:
      - mongodb
      - nsqd
    ports:
      - "8080:8080" # api (http endpoints)
      - "8081:8081" # web (http server
    volumes:
      - .:/home
