@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()

title Shipyard - Components

Container_Boundary(Shipyard, "Shipyard") {
    Component(ropeworks, "Ropeworks", "Module", "produces ropes")
    Component(mastworks, "Mastworks", "Module", "produces masts")
    Component(sailworks, "Sailworks", "Module", "produces sails")
}
Container(Sawmill, "Sawmill", "Container", "produces planks")
Rel_Neighbor(Shipyard, Sawmill, "Uses", "grpc")
@enduml