---
apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    # add "Logs for this span" button in span view
    jsonData:
      grpcEndpoint: tempo:9095
      tracesToLogsV2:
        datasourceUid: loki
        customQuery: true
        query: '{service_name=~".+"} | trace_id=`$${__trace.traceId}` | span_id=`$${__span.spanId}`'
        tags:
          - key: service.name
            value: service_name
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    # add "View Trace" button in log entry view
    jsonData:
      derivedFields:
        - name: TraceID
          matcherType: label
          matcherRegex: trace[_]?id
          url: '$${__value.raw}'
          datasourceUid: tempo
          urlDisplayLabel: View Trace
          
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
