@startuml
'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
 !include SoftwareDevelopment/DNA/C4/C4PUML/C4-PlantUML/C4_Component.puml

title Component-Level diagram for xkcd
#Person(user, "comic book reader")
System_Ext(xkcd_online_service, "xkcd service", "comic book online service")
ContainerDb(comic_book_storage, "storage", "comic book offline storage")
Container_Boundary(browser, "browser") {
    Component(fetcher, "xkcd fetcher", "fetch comic books from external service and convert to internal data model")
    Component(repository, "comic book repository", "store comic book series offline") 
    Component(printer, "comic book presenter", "present comic book to user") 
    Component(cli, "cli", "command line interface") 
    Component(controller, "controller", "controller") 
}
Rel(fetcher, xkcd_online_service, "fetch comic books", "http/get+json")
Rel(repository, comic_book_storage, "store/read comic books", "json")
Rel(user, cli, "enter cli commands")
Rel_D(cli, controller, "send commands/receive response over [io.Writer, error] interface")
Rel(controller, fetcher, "fetch online comic books")
Rel(controller, repository, "load/store offline comic books, store new titles")
Rel(controller, printer, "present comic book")
@enduml
