// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mateuszmidor/GoStudy/swagger/generated_client/models"
)

// GetProductsNameReader is a Reader for the GetProductsName structure.
type GetProductsNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProductsNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProductsNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetProductsNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProductsNameOK creates a GetProductsNameOK with default headers values
func NewGetProductsNameOK() *GetProductsNameOK {
	return &GetProductsNameOK{}
}

/* GetProductsNameOK describes a response with status code 200, with default header values.

Get products success
*/
type GetProductsNameOK struct {
	Payload *models.Product
}

func (o *GetProductsNameOK) Error() string {
	return fmt.Sprintf("[GET /products/{name}][%d] getProductsNameOK  %+v", 200, o.Payload)
}
func (o *GetProductsNameOK) GetPayload() *models.Product {
	return o.Payload
}

func (o *GetProductsNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Product)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProductsNameNotFound creates a GetProductsNameNotFound with default headers values
func NewGetProductsNameNotFound() *GetProductsNameNotFound {
	return &GetProductsNameNotFound{}
}

/* GetProductsNameNotFound describes a response with status code 404, with default header values.

No such product in the fridge
*/
type GetProductsNameNotFound struct {
}

func (o *GetProductsNameNotFound) Error() string {
	return fmt.Sprintf("[GET /products/{name}][%d] getProductsNameNotFound ", 404)
}

func (o *GetProductsNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
