// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProductsNameParams creates a new GetProductsNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProductsNameParams() *GetProductsNameParams {
	return &GetProductsNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProductsNameParamsWithTimeout creates a new GetProductsNameParams object
// with the ability to set a timeout on a request.
func NewGetProductsNameParamsWithTimeout(timeout time.Duration) *GetProductsNameParams {
	return &GetProductsNameParams{
		timeout: timeout,
	}
}

// NewGetProductsNameParamsWithContext creates a new GetProductsNameParams object
// with the ability to set a context for a request.
func NewGetProductsNameParamsWithContext(ctx context.Context) *GetProductsNameParams {
	return &GetProductsNameParams{
		Context: ctx,
	}
}

// NewGetProductsNameParamsWithHTTPClient creates a new GetProductsNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProductsNameParamsWithHTTPClient(client *http.Client) *GetProductsNameParams {
	return &GetProductsNameParams{
		HTTPClient: client,
	}
}

/* GetProductsNameParams contains all the parameters to send to the API endpoint
   for the get products name operation.

   Typically these are written to a http.Request.
*/
type GetProductsNameParams struct {

	/* Name.

	   Name of the product to get information about
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get products name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProductsNameParams) WithDefaults() *GetProductsNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get products name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProductsNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get products name params
func (o *GetProductsNameParams) WithTimeout(timeout time.Duration) *GetProductsNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get products name params
func (o *GetProductsNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get products name params
func (o *GetProductsNameParams) WithContext(ctx context.Context) *GetProductsNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get products name params
func (o *GetProductsNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get products name params
func (o *GetProductsNameParams) WithHTTPClient(client *http.Client) *GetProductsNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get products name params
func (o *GetProductsNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get products name params
func (o *GetProductsNameParams) WithName(name string) *GetProductsNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get products name params
func (o *GetProductsNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetProductsNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
