// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutProductsNameParams creates a new PutProductsNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutProductsNameParams() *PutProductsNameParams {
	return &PutProductsNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutProductsNameParamsWithTimeout creates a new PutProductsNameParams object
// with the ability to set a timeout on a request.
func NewPutProductsNameParamsWithTimeout(timeout time.Duration) *PutProductsNameParams {
	return &PutProductsNameParams{
		timeout: timeout,
	}
}

// NewPutProductsNameParamsWithContext creates a new PutProductsNameParams object
// with the ability to set a context for a request.
func NewPutProductsNameParamsWithContext(ctx context.Context) *PutProductsNameParams {
	return &PutProductsNameParams{
		Context: ctx,
	}
}

// NewPutProductsNameParamsWithHTTPClient creates a new PutProductsNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutProductsNameParamsWithHTTPClient(client *http.Client) *PutProductsNameParams {
	return &PutProductsNameParams{
		HTTPClient: client,
	}
}

/* PutProductsNameParams contains all the parameters to send to the API endpoint
   for the put products name operation.

   Typically these are written to a http.Request.
*/
type PutProductsNameParams struct {

	/* Name.

	   Name of the product to withdraw from the fridge
	*/
	Name string

	/* Product.

	   Amount of the product to withdraw from the fridge
	*/
	Product PutProductsNameBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put products name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProductsNameParams) WithDefaults() *PutProductsNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put products name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProductsNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put products name params
func (o *PutProductsNameParams) WithTimeout(timeout time.Duration) *PutProductsNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put products name params
func (o *PutProductsNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put products name params
func (o *PutProductsNameParams) WithContext(ctx context.Context) *PutProductsNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put products name params
func (o *PutProductsNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put products name params
func (o *PutProductsNameParams) WithHTTPClient(client *http.Client) *PutProductsNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put products name params
func (o *PutProductsNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the put products name params
func (o *PutProductsNameParams) WithName(name string) *PutProductsNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the put products name params
func (o *PutProductsNameParams) SetName(name string) {
	o.Name = name
}

// WithProduct adds the product to the put products name params
func (o *PutProductsNameParams) WithProduct(product PutProductsNameBody) *PutProductsNameParams {
	o.SetProduct(product)
	return o
}

// SetProduct adds the product to the put products name params
func (o *PutProductsNameParams) SetProduct(product PutProductsNameBody) {
	o.Product = product
}

// WriteToRequest writes these params to a swagger request
func (o *PutProductsNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.Product); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
