/*
Fridge API

OpenAPI 3.0.0 study - a fridge API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ProductsNamePutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductsNamePutRequest{}

// ProductsNamePutRequest struct for ProductsNamePutRequest
type ProductsNamePutRequest struct {
	Quantity *float32 `json:"quantity,omitempty"`
}

// NewProductsNamePutRequest instantiates a new ProductsNamePutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductsNamePutRequest() *ProductsNamePutRequest {
	this := ProductsNamePutRequest{}
	var quantity float32 = 1
	this.Quantity = &quantity
	return &this
}

// NewProductsNamePutRequestWithDefaults instantiates a new ProductsNamePutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductsNamePutRequestWithDefaults() *ProductsNamePutRequest {
	this := ProductsNamePutRequest{}
	var quantity float32 = 1
	this.Quantity = &quantity
	return &this
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *ProductsNamePutRequest) GetQuantity() float32 {
	if o == nil || IsNil(o.Quantity) {
		var ret float32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductsNamePutRequest) GetQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *ProductsNamePutRequest) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float32 and assigns it to the Quantity field.
func (o *ProductsNamePutRequest) SetQuantity(v float32) {
	o.Quantity = &v
}

func (o ProductsNamePutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductsNamePutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	return toSerialize, nil
}

type NullableProductsNamePutRequest struct {
	value *ProductsNamePutRequest
	isSet bool
}

func (v NullableProductsNamePutRequest) Get() *ProductsNamePutRequest {
	return v.value
}

func (v *NullableProductsNamePutRequest) Set(val *ProductsNamePutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductsNamePutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductsNamePutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductsNamePutRequest(val *ProductsNamePutRequest) *NullableProductsNamePutRequest {
	return &NullableProductsNamePutRequest{value: val, isSet: true}
}

func (v NullableProductsNamePutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductsNamePutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


