// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Fridge API
 *
 * OpenAPI 3.0.0 study - a fridge API
 *
 * API version: 0.0.1
 */

package server

import (
	"context"
	"net/http"
)



// DefaultAPIRouter defines the required methods for binding the api requests to a responses for the DefaultAPI
// The DefaultAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultAPIServicer to perform the required actions, then write the service results to the http response.
type DefaultAPIRouter interface { 
	ProductsGet(http.ResponseWriter, *http.Request)
	ProductsPost(http.ResponseWriter, *http.Request)
	ProductsNameGet(http.ResponseWriter, *http.Request)
	ProductsNamePut(http.ResponseWriter, *http.Request)
}


// DefaultAPIServicer defines the api actions for the DefaultAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultAPIServicer interface { 
	ProductsGet(context.Context, bool) (ImplResponse, error)
	ProductsPost(context.Context, Product) (ImplResponse, error)
	ProductsNameGet(context.Context, string) (ImplResponse, error)
	ProductsNamePut(context.Context, string, ProductsNamePutRequest) (ImplResponse, error)
}
