// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Fridge API
 *
 * OpenAPI 3.0.0 study - a fridge API
 *
 * API version: 0.0.1
 */

package server


import (
	"errors"
)



// Product - Single product
type Product struct {

	Name string `json:"name,omitempty"`

	Quantity float32 `json:"quantity,omitempty"`
}

// AssertProductRequired checks if the required fields are not zero-ed
func AssertProductRequired(obj Product) error {
	return nil
}

// AssertProductConstraints checks if the values respects the defined constraints
func AssertProductConstraints(obj Product) error {
	if obj.Quantity < 0.0 {
		return &ParsingError{Param: "Quantity", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
