// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Fridge API
 *
 * OpenAPI 3.0.0 study - a fridge API
 *
 * API version: 0.0.1
 */

package server

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// DefaultAPIController binds http requests to an api service and writes the service results to the http response
type DefaultAPIController struct {
	service DefaultAPIServicer
	errorHandler ErrorHandler
}

// DefaultAPIOption for how the controller is set up.
type DefaultAPIOption func(*DefaultAPIController)

// WithDefaultAPIErrorHandler inject ErrorHandler into controller
func WithDefaultAPIErrorHandler(h ErrorHandler) DefaultAPIOption {
	return func(c *DefaultAPIController) {
		c.errorHandler = h
	}
}

// NewDefaultAPIController creates a default api controller
func NewDefaultAPIController(s DefaultAPIServicer, opts ...DefaultAPIOption) *DefaultAPIController {
	controller := &DefaultAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the DefaultAPIController
func (c *DefaultAPIController) Routes() Routes {
	return Routes{
		"ProductsGet": Route{
			"ProductsGet",
			strings.ToUpper("Get"),
			"/products",
			c.ProductsGet,
		},
		"ProductsPost": Route{
			"ProductsPost",
			strings.ToUpper("Post"),
			"/products",
			c.ProductsPost,
		},
		"ProductsNameGet": Route{
			"ProductsNameGet",
			strings.ToUpper("Get"),
			"/products/{name}",
			c.ProductsNameGet,
		},
		"ProductsNamePut": Route{
			"ProductsNamePut",
			strings.ToUpper("Put"),
			"/products/{name}",
			c.ProductsNamePut,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the DefaultAPIController
func (c *DefaultAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"ProductsGet",
			strings.ToUpper("Get"),
			"/products",
			c.ProductsGet,
		},
		Route{
			"ProductsPost",
			strings.ToUpper("Post"),
			"/products",
			c.ProductsPost,
		},
		Route{
			"ProductsNameGet",
			strings.ToUpper("Get"),
			"/products/{name}",
			c.ProductsNameGet,
		},
		Route{
			"ProductsNamePut",
			strings.ToUpper("Put"),
			"/products/{name}",
			c.ProductsNamePut,
		},
	}
}



// ProductsGet - 
func (c *DefaultAPIController) ProductsGet(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var sortParam bool
	if query.Has("sort") {
		param, err := parseBoolParameter(
			query.Get("sort"),
			WithParse[bool](parseBool),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "sort", Err: err}, nil)
			return
		}

		sortParam = param
	} else {
		var param bool = false
		sortParam = param
	}
	result, err := c.service.ProductsGet(r.Context(), sortParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ProductsPost - 
func (c *DefaultAPIController) ProductsPost(w http.ResponseWriter, r *http.Request) {
	var productParam Product
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&productParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertProductRequired(productParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertProductConstraints(productParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ProductsPost(r.Context(), productParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ProductsNameGet - 
func (c *DefaultAPIController) ProductsNameGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	nameParam := params["name"]
	if nameParam == "" {
		c.errorHandler(w, r, &RequiredError{"name"}, nil)
		return
	}
	result, err := c.service.ProductsNameGet(r.Context(), nameParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ProductsNamePut - 
func (c *DefaultAPIController) ProductsNamePut(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	nameParam := params["name"]
	if nameParam == "" {
		c.errorHandler(w, r, &RequiredError{"name"}, nil)
		return
	}
	var productsNamePutRequestParam ProductsNamePutRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&productsNamePutRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertProductsNamePutRequestRequired(productsNamePutRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertProductsNamePutRequestConstraints(productsNamePutRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ProductsNamePut(r.Context(), nameParam, productsNamePutRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
