// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Fridge API
 *
 * OpenAPI 3.0.0 study - a fridge API
 *
 * API version: 0.0.1
 */

package server


import (
	"errors"
)



type ProductsNamePutRequest struct {

	Quantity float32 `json:"quantity,omitempty"`
}

// AssertProductsNamePutRequestRequired checks if the required fields are not zero-ed
func AssertProductsNamePutRequestRequired(obj ProductsNamePutRequest) error {
	return nil
}

// AssertProductsNamePutRequestConstraints checks if the values respects the defined constraints
func AssertProductsNamePutRequestConstraints(obj ProductsNamePutRequest) error {
	if obj.Quantity < 0.0 {
		return &ParsingError{Param: "Quantity", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
