// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Product Single product
type Product struct {
	// Name Example: Milk
	Name *ProductName `json:"name,omitempty"`

	// Quantity Example: 0.5
	Quantity *float32 `json:"quantity,omitempty"`
}

// ProductName Example: Milk
type ProductName = string

// Products List of products
type Products = []Product

// GetProductsParams defines parameters for GetProducts.
type GetProductsParams struct {
	// Sort Sort products alphabetically A to Z
	Sort *bool `form:"sort,omitempty" json:"sort,omitempty"`
}

// PutProductsNameJSONBody defines parameters for PutProductsName.
type PutProductsNameJSONBody struct {
	// Quantity Example: 1
	Quantity *float32 `json:"quantity,omitempty"`
}

// PostProductsJSONRequestBody defines body for PostProducts for application/json ContentType.
type PostProductsJSONRequestBody = Product

// PutProductsNameJSONRequestBody defines body for PutProductsName for application/json ContentType.
type PutProductsNameJSONRequestBody PutProductsNameJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetProducts performs a GET /products (the `GetProducts` operationId) request.
	//
	// List all products in the fridge.
	GetProducts(ctx context.Context, params *GetProductsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostProductsWithBody performs a POST /products (the `PostProducts` operationId) request,
	// with any type of body and a specified content type.
	//
	// Insert more of a product into the fridge.
	PostProductsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostProducts performs a POST /products (the `PostProducts` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Insert more of a product into the fridge.
	PostProducts(ctx context.Context, body PostProductsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProductsName performs a GET /products/{name} (the `GetProductsName` operationId) request.
	//
	// Get single product information.
	GetProductsName(ctx context.Context, name ProductName, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutProductsNameWithBody performs a PUT /products/{name} (the `PutProductsName` operationId) request,
	// with any type of body and a specified content type.
	//
	// Withdraw given amount of given product from the fridge.
	PutProductsNameWithBody(ctx context.Context, name ProductName, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutProductsName performs a PUT /products/{name} (the `PutProductsName` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Withdraw given amount of given product from the fridge.
	PutProductsName(ctx context.Context, name ProductName, body PutProductsNameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetProducts performs a GET /products (the `GetProducts` operationId) request.
//
// List all products in the fridge.
func (c *Client) GetProducts(ctx context.Context, params *GetProductsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProductsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostProductsWithBody performs a POST /products (the `PostProducts` operationId) request,
// with any type of body and a specified content type.
//
// Insert more of a product into the fridge.
func (c *Client) PostProductsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostProductsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostProducts performs a POST /products (the `PostProducts` operationId) request.
// Takes a body of the `application/json` content type.
//
// Insert more of a product into the fridge.
func (c *Client) PostProducts(ctx context.Context, body PostProductsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostProductsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetProductsName performs a GET /products/{name} (the `GetProductsName` operationId) request.
//
// Get single product information.
func (c *Client) GetProductsName(ctx context.Context, name ProductName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProductsNameRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutProductsNameWithBody performs a PUT /products/{name} (the `PutProductsName` operationId) request,
// with any type of body and a specified content type.
//
// Withdraw given amount of given product from the fridge.
func (c *Client) PutProductsNameWithBody(ctx context.Context, name ProductName, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutProductsNameRequestWithBody(c.Server, name, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutProductsName performs a PUT /products/{name} (the `PutProductsName` operationId) request.
// Takes a body of the `application/json` content type.
//
// Withdraw given amount of given product from the fridge.
func (c *Client) PutProductsName(ctx context.Context, name ProductName, body PutProductsNameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutProductsNameRequest(c.Server, name, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetProductsRequest constructs an http.Request for the GetProducts method
func NewGetProductsRequest(server string, params *GetProductsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/products")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort", *params.Sort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostProductsRequest calls the generic PostProducts builder with application/json body
func NewPostProductsRequest(server string, body PostProductsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostProductsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostProductsRequestWithBody constructs an http.Request for the PostProducts method, with any body, and a specified content type
func NewPostProductsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/products")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetProductsNameRequest constructs an http.Request for the GetProductsName method
func NewGetProductsNameRequest(server string, name ProductName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/products/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutProductsNameRequest calls the generic PutProductsName builder with application/json body
func NewPutProductsNameRequest(server string, name ProductName, body PutProductsNameJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutProductsNameRequestWithBody(server, name, "application/json", bodyReader)
}

// NewPutProductsNameRequestWithBody constructs an http.Request for the PutProductsName method, with any body, and a specified content type
func NewPutProductsNameRequestWithBody(server string, name ProductName, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/products/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetProductsWithResponse performs a GET /products (the `GetProducts` operationId) request.
	//
	// List all products in the fridge.
	//
	// Returns a wrapper object for the known response body format(s).
	GetProductsWithResponse(ctx context.Context, params *GetProductsParams, reqEditors ...RequestEditorFn) (*GetProductsResponse, error)

	// PostProductsWithBodyWithResponse performs a POST /products (the `PostProducts` operationId) request,
	// with any type of body and a specified content type.
	//
	// Insert more of a product into the fridge.
	//
	// Returns a wrapper object for the known response body format(s).
	PostProductsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostProductsResponse, error)

	// PostProductsWithResponse performs a POST /products (the `PostProducts` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Insert more of a product into the fridge.
	PostProductsWithResponse(ctx context.Context, body PostProductsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostProductsResponse, error)

	// GetProductsNameWithResponse performs a GET /products/{name} (the `GetProductsName` operationId) request.
	//
	// Get single product information.
	//
	// Returns a wrapper object for the known response body format(s).
	GetProductsNameWithResponse(ctx context.Context, name ProductName, reqEditors ...RequestEditorFn) (*GetProductsNameResponse, error)

	// PutProductsNameWithBodyWithResponse performs a PUT /products/{name} (the `PutProductsName` operationId) request,
	// with any type of body and a specified content type.
	//
	// Withdraw given amount of given product from the fridge.
	//
	// Returns a wrapper object for the known response body format(s).
	PutProductsNameWithBodyWithResponse(ctx context.Context, name ProductName, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutProductsNameResponse, error)

	// PutProductsNameWithResponse performs a PUT /products/{name} (the `PutProductsName` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Withdraw given amount of given product from the fridge.
	PutProductsNameWithResponse(ctx context.Context, name ProductName, body PutProductsNameJSONRequestBody, reqEditors ...RequestEditorFn) (*PutProductsNameResponse, error)
}

type GetProductsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Products
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetProductsResponse) GetJSON200() *Products {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetProductsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetProductsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProductsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetProductsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostProductsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r PostProductsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostProductsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostProductsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostProductsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetProductsNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Product
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetProductsNameResponse) GetJSON200() *Product {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetProductsNameResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetProductsNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProductsNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetProductsNameResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutProductsNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r PutProductsNameResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PutProductsNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutProductsNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutProductsNameResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetProductsWithResponse performs a GET /products (the `GetProducts` operationId) request.
//
// List all products in the fridge.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetProductsWithResponse(ctx context.Context, params *GetProductsParams, reqEditors ...RequestEditorFn) (*GetProductsResponse, error) {
	rsp, err := c.GetProducts(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProductsResponse(rsp)
}

// PostProductsWithBodyWithResponse performs a POST /products (the `PostProducts` operationId) request,
// with any type of body and a specified content type.
//
// Insert more of a product into the fridge.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostProductsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostProductsResponse, error) {
	rsp, err := c.PostProductsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostProductsResponse(rsp)
}

// PostProductsWithResponse performs a POST /products (the `PostProducts` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Insert more of a product into the fridge.
func (c *ClientWithResponses) PostProductsWithResponse(ctx context.Context, body PostProductsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostProductsResponse, error) {
	rsp, err := c.PostProducts(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostProductsResponse(rsp)
}

// GetProductsNameWithResponse performs a GET /products/{name} (the `GetProductsName` operationId) request.
//
// Get single product information.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetProductsNameWithResponse(ctx context.Context, name ProductName, reqEditors ...RequestEditorFn) (*GetProductsNameResponse, error) {
	rsp, err := c.GetProductsName(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProductsNameResponse(rsp)
}

// PutProductsNameWithBodyWithResponse performs a PUT /products/{name} (the `PutProductsName` operationId) request,
// with any type of body and a specified content type.
//
// Withdraw given amount of given product from the fridge.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PutProductsNameWithBodyWithResponse(ctx context.Context, name ProductName, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutProductsNameResponse, error) {
	rsp, err := c.PutProductsNameWithBody(ctx, name, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutProductsNameResponse(rsp)
}

// PutProductsNameWithResponse performs a PUT /products/{name} (the `PutProductsName` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Withdraw given amount of given product from the fridge.
func (c *ClientWithResponses) PutProductsNameWithResponse(ctx context.Context, name ProductName, body PutProductsNameJSONRequestBody, reqEditors ...RequestEditorFn) (*PutProductsNameResponse, error) {
	rsp, err := c.PutProductsName(ctx, name, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutProductsNameResponse(rsp)
}

// ParseGetProductsResponse parses an HTTP response from a GetProductsWithResponse call
func ParseGetProductsResponse(rsp *http.Response) (*GetProductsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProductsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Products
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostProductsResponse parses an HTTP response from a PostProductsWithResponse call
func ParsePostProductsResponse(rsp *http.Response) (*PostProductsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostProductsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetProductsNameResponse parses an HTTP response from a GetProductsNameWithResponse call
func ParseGetProductsNameResponse(rsp *http.Response) (*GetProductsNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProductsNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Product
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 404:
		break // No content-type

	}

	return response, nil
}

// ParsePutProductsNameResponse parses an HTTP response from a PutProductsNameWithResponse call
func ParsePutProductsNameResponse(rsp *http.Response) (*PutProductsNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutProductsNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
